name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
      - 'hotfix/*'
  push:
    branches:
      - 'master'
      - 'hotfix/*'

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: |
          echo -e "storeFile=\"storeFile\"\nstorePassword=\"storePassword\"\nkeyAlias=\"keyAlias\"\nkeyPassword=\"keyPassword\"" > keystore.properties
          bash ./gradlew testReleaseUnitTest --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        env:
          RELEASE_API_KEY: ${{ secrets.RELEASE_API_KEY }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$RELEASE_KEYSTORE" > release.keystore.asc
          gpg -d --passphrase "$STORE_PASSWORD" --batch release.keystore.asc > app/release.keystore
          echo -e "storeFile=release.keystore\nstorePassword=$STORE_PASSWORD\nkeyAlias=$KEY_ALIAS\nkeyPassword=$KEY_PASSWORD" > keystore.properties
          bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk
